export { ReactComponent as IcoBack} from './back.svg'
export { ReactComponent as IcoMenu} from './menu.svg'
export { ReactComponent as IcoSearch} from './search.svg'
export { ReactComponent as IcoBell} from './bell.svg'
export { ReactComponent as IcoAdd} from './add.svg'