import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      {/* https://projects.invisionapp.com/share/JZRMNHUH2BC */}
      <Head>
        <title>
          리바트몰
          {/* 버스커:우리 동네 길거리 음식은 어디? - 버거,스테이크,커리 - */}
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>test</main>
    </div>
  );
};

export default Home;
